language: php
dist: xenial

php:
  - 7.3

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

branches:
  only:
    # Standard branch e.g. 8.x-1.x
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/
    # Any issue branch starting with 7 digits followed by -
    - /^[0-9]{7}\-.*/

env:
  matrix:
    - DRUPAL_TESTING_TEST_LOCATION="modules/contrib/scheduler_content_moderation_integration"
    - DRUPAL_TESTING_TEST_LOCATION="modules/contrib/scheduler"

  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin:$HOME/.config/composer/vendor/bin"
    - DRUPAL_TESTING_TEST_JAVASCRIPT=false

before_install:
  - composer global require thunder/drupal-testing
  - test-drupal-project prepare_build

  # required modules for scheduler tests.
  - composer require drupal/rules --no-update --working-dir=/tmp/test/scheduler_content_moderation_integration/install
  - composer require drupal/devel --no-update --working-dir=/tmp/test/scheduler_content_moderation_integration/install
  - composer require drupal/typed_data --no-update --working-dir=/tmp/test/scheduler_content_moderation_integration/install

before_script:
  - phpenv config-rm xdebug.ini

script:
  - test-drupal-project
